status

diff --git a/.github/workflows/site.yml b/.github/workflows/site.yml
--- a/.github/workflows/site.yml
+++ b/.github/workflows/site.yml
@@ -135,22 +135,17 @@ jobs:
       uses: actions/checkout@v4
       with:
         fetch-depth: '0'
-    - name: Generate a token
+    - name: Generate Token
       id: generate-token
-      uses: actions/create-github-app-token@v1.11.1
+      uses: zio/generate-github-app-token@v1.0.0
       with:
-        app-id: ${{ secrets.APP_ID }}
-        private-key: ${{ secrets.APP_PRIVATE_KEY }}
-        owner: ${{ github.repository_owner }}
-#    - name: Generate Token
-#      id: generate-token
-#      uses: zio/generate-github-app-token@v1.0.0
-#      with:
-#        app_id: ${{ secrets.APP_ID }}
-#        app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
+        app_id: ${{ secrets.APP_ID }}
+        app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
     - name: notify the main repo about the new release of docs package
       run: |
-        curl -L \
+        PACKAGE_NAME=$(cat docs/package.json | grep '"name"' | awk -F'"' '{print $4}')
+        PACKAGE_VERSION=$(npm view $PACKAGE_NAME version)
+        response=$(curl -L  -w "%{http_code}" \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: token ${{ steps.generate-token.outputs.token }}"\
@@ -161,4 +156,11 @@ jobs:
                     "package_name":"test-name",
                     "package_version": "test-version"
                   }
-                }'
+                }')
+        
+        status_code=$(echo "$response" | tail -n 1)
+        echo "$response"
+        if [ "$status_code" != "200" ]; then
+          echo "Error: Expected status code 200, got $status_code"
+          exit 1
+        fi
